services:
  pg:
    image: postgres
    container_name: ai_pg
    hostname: pg.dev
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: ai_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - db-network
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ai_bot
    environment:
      - PYTHONUNBUFFERED=1
    env_file: .env
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
      - db-network
      - redis-network
  redis:
    image: redis:latest
    container_name: ai_redis
    restart: unless-stopped
    volumes:
      - redis_data:/root/redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
    networks:
      - redis-network
  ollama:
    image: ollama/ollama
    profiles:
      - exclude
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    networks:
      - app-network

volumes:
  pgdata:
  redis_data:
  ollama:

networks:
  app-network:
  redis-network:
  db-network:
